name: Build Mac and Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for the Mac build (e.g. 0.9.8)"
        required: true

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      # 1) Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Bump version
      - name: Set app version
        run: |
          echo "Bumping version to ${{ github.event.inputs.version }}"
          npm version ${{ github.event.inputs.version }} --allow-same-version --no-git-tag-version

      # 3) Install Developer ID Certificate
      - name: Install Developer ID Certificate
        run: |
          # 3.1 Decode the base64-encoded p12
          echo "${{ secrets.MAC_CERT_P12 }}" | base64 --decode > /tmp/cert.p12

          # 3.2 Create an empty-password keychain
          security create-keychain -p "" build.keychain
          security set-keychain-settings build.keychain

          # 3.3 Add the new keychain to the search list, set it as default
          security list-keychains -s build.keychain $(security list-keychains -s | tr -d '"')
          security default-keychain -s build.keychain

          # 3.4 Unlock keychain
          security unlock-keychain -p "" build.keychain

          # 3.5 Import p12 using the password
          security import /tmp/cert.p12 -k build.keychain \
            -P "${{ secrets.MAC_CERT_PW }}" \
            -T /usr/bin/codesign -T /usr/bin/security

          # 3.6 Allow codesign to use the key
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      # 4) Download demucs-cxfreeze-mac.zip from 'release-assets'
      - name: Download demucs-cxfreeze-mac.zip
        run: |
          curl -L \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://github.com/davidcamick/CamStem/releases/download/release-assets/demucs-cxfreeze-mac.zip" \
            -o demucs-cxfreeze-mac.zip

          rm -rf src/backend/demucs-cxfreeze-mac
          unzip -q demucs-cxfreeze-mac.zip -d src/backend
          rm demucs-cxfreeze-mac.zip

      # 5) Download Models.zip from 'release-assets'
      - name: Download Models.zip
        run: |
          curl -L \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://github.com/davidcamick/CamStem/releases/download/release-assets/Models.zip" \
            -o Models.zip

          rm -rf Models
          unzip -q Models.zip -d .
          rm Models.zip

      # 6) Install dependencies
      - name: Install dependencies
        run: npm install

      # 7) Build & publish
      - name: Build Mac (publish to GitHub)
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # Apple Developer email
          APPLE_ID: ${{ secrets.APPLE_ID }}

          # Electron-builder 25+ expects these EXACT variable names
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
