name: Build Windows

on:
  push:
    tags:
      - "v*" # e.g. v0.9.7.1

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Configure GH_TOKEN
        # Provide GH_TOKEN to electron-builder so it can publish
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Build Windows
        shell: bash
        run: |
          npm run build:win
