name: Build Mac and Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for the Mac build (e.g. 0.9.8)"
        required: true

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      # 1) Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Bump version in package.json (but don't create a local git tag)
      - name: Set app version
        run: |
          echo "Bumping version to ${{ github.event.inputs.version }}"
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      # 3) Download demucs-cxfreeze-mac.zip from your 'release-assets' release
      - name: Download demucs-cxfreeze-mac.zip
        run: |
          echo "Fetching release data from 'release-assets'..."
          RELEASE_DATA=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/davidcamick/camstem/releases/tags/release-assets")

          ASSET_ID=$(echo "$RELEASE_DATA" | \
            jq -r '.assets[] | select(.name=="demucs-cxfreeze-mac.zip") | .id')

          if [ -z "$ASSET_ID" ] || [ "$ASSET_ID" == "null" ]; then
            echo "Could not find demucs-cxfreeze-mac.zip in release-assets!"
            exit 1
          fi

          echo "Downloading demucs-cxfreeze-mac.zip (asset id=$ASSET_ID) ..."
          curl -L \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/davidcamick/camstem/releases/assets/$ASSET_ID" \
            -o demucs-cxfreeze-mac.zip

          # Remove old folder, then unzip into src/backend
          rm -rf src/backend/demucs-cxfreeze-mac
          unzip -q demucs-cxfreeze-mac.zip -d src/backend
          rm demucs-cxfreeze-mac.zip

      # 4) Download Models.zip from 'release-assets'
      - name: Download Models.zip
        run: |
          RELEASE_DATA=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/davidcamick/camstem/releases/tags/release-assets")

          ASSET_ID=$(echo "$RELEASE_DATA" | \
            jq -r '.assets[] | select(.name=="Models.zip") | .id')

          if [ -z "$ASSET_ID" ] || [ "$ASSET_ID" == "null" ]; then
            echo "Could not find Models.zip in release-assets!"
            exit 1
          fi

          echo "Downloading Models.zip (asset id=$ASSET_ID) ..."
          curl -L \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/davidcamick/camstem/releases/assets/$ASSET_ID" \
            -o Models.zip

          # Remove old folder, then unzip at project root -> creates 'Models/'
          rm -rf Models
          unzip -q Models.zip -d .
          rm Models.zip

      # 5) Install dependencies
      - name: Install dependencies
        run: npm install

      # 6) Build & publish to CamStemReleases
      - name: Build Mac (publish to GitHub)
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
