name: Build Mac and Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for the Mac build (e.g. 0.9.8)"
        required: true

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      # 1) Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Bump version
      - name: Set app version
        run: |
          echo "Bumping version to ${{ github.event.inputs.version }}"
          npm version ${{ github.event.inputs.version }} --allow-same-version --no-git-tag-version

      # 3) Install Developer ID Certificate
      - name: Install Developer ID Certificate
        run: |
          # 3.1 Decode the base64-encoded p12
          echo "${{ secrets.MAC_CERT_P12 }}" | base64 --decode > /tmp/cert.p12

          # 3.2 Create an empty-password keychain
          security create-keychain -p "" build.keychain
          security set-keychain-settings build.keychain

          # 3.3 Add the new keychain to the search list, set it as default
          security list-keychains -s build.keychain $(security list-keychains -s | tr -d '"')
          security default-keychain -s build.keychain

          # 3.4 Unlock keychain
          security unlock-keychain -p "" build.keychain

          # 3.5 Import p12 using the password
          security import /tmp/cert.p12 -k build.keychain \
            -P "${{ secrets.MAC_CERT_PW }}" \
            -T /usr/bin/codesign -T /usr/bin/security

          # 3.6 Allow codesign to use the key
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      # 4) Download CamStemExtension.zip from 'release-assets'
      - name: Download CamStemExtension.zip
        run: |
          echo "Fetching releases list..."
          RELEASES=$(curl -sL \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/davidcamick/camstem/releases")
          
          if [ $? -ne 0 ]; then
            echo "Failed to fetch releases"
            exit 1
          fi
          
          # Find the release with tag "release-assets"
          RELEASE_ID=$(echo "$RELEASES" | jq -r '.[] | select(.tag_name=="release-assets") | .id')
          
          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" == "null" ]; then
            echo "Could not find release with tag 'release-assets'"
            exit 1
          fi
          
          echo "Found release with ID: $RELEASE_ID"
          
          # Get asset ID for CamStemExtension.zip
          ASSET_ID=$(curl -sL \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/davidcamick/camstem/releases/$RELEASE_ID" | \
            jq -r '.assets[] | select(.name=="CamStemExtension.zip") | .id')
          
          if [ -z "$ASSET_ID" ] || [ "$ASSET_ID" == "null" ]; then
            echo "Could not find CamStemExtension.zip in release assets"
            exit 1
          fi
          
          echo "Downloading asset ID: $ASSET_ID"
          curl -LJ \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/davidcamick/camstem/releases/assets/$ASSET_ID" \
            -o CamStemExtension.zip

          if [ ! -f CamStemExtension.zip ]; then
            echo "Failed to download CamStemExtension.zip"
            exit 1
          fi

          rm -rf src/backend/CamStemExtension
          unzip -q CamStemExtension.zip -d src/backend
          rm CamStemExtension.zip

      # 5) Download demucs-cxfreeze-mac.zip from 'release-assets'
      - name: Download demucs-cxfreeze-mac.zip
        run: |
          echo "Fetching releases list..."
          RELEASES=$(curl -sL \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/davidcamick/camstem/releases")
          
          if [ $? -ne 0 ]; then
            echo "Failed to fetch releases"
            exit 1
          fi
          
          # Find the release with tag "release-assets"
          RELEASE_ID=$(echo "$RELEASES" | jq -r '.[] | select(.tag_name=="release-assets") | .id')
          
          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" == "null" ]; then
            echo "Could not find release with tag 'release-assets'"
            exit 1
          fi
          
          echo "Found release with ID: $RELEASE_ID"
          
          # Get asset ID
          ASSET_ID=$(curl -sL \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/davidcamick/camstem/releases/$RELEASE_ID" | \
            jq -r '.assets[] | select(.name=="demucs-cxfreeze-mac.zip") | .id')
          
          if [ -z "$ASSET_ID" ] || [ "$ASSET_ID" == "null" ]; then
            echo "Could not find demucs-cxfreeze-mac.zip in release assets"
            exit 1
          fi
          
          echo "Downloading asset ID: $ASSET_ID"
          curl -LJ \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/davidcamick/camstem/releases/assets/$ASSET_ID" \
            -o demucs-cxfreeze-mac.zip

          if [ ! -f demucs-cxfreeze-mac.zip ]; then
            echo "Failed to download demucs-cxfreeze-mac.zip"
            exit 1
          fi

          rm -rf src/backend/demucs-cxfreeze-mac
          unzip -q demucs-cxfreeze-mac.zip -d src/backend
          rm demucs-cxfreeze-mac.zip

      # 6) Download Models.zip from 'release-assets'
      - name: Download Models.zip
        run: |
          echo "Fetching releases list..."
          RELEASES=$(curl -sL \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/davidcamick/camstem/releases")
          
          if [ $? -ne 0 ]; then
            echo "Failed to fetch releases"
            exit 1
          fi
          
          # Find the release with tag "release-assets"
          RELEASE_ID=$(echo "$RELEASES" | jq -r '.[] | select(.tag_name=="release-assets") | .id')
          
          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" == "null" ]; then
            echo "Could not find release with tag 'release-assets'"
            exit 1
          fi
          
          echo "Found release with ID: $RELEASE_ID"
          
          # Get asset ID
          ASSET_ID=$(curl -sL \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/davidcamick/camstem/releases/$RELEASE_ID" | \
            jq -r '.assets[] | select(.name=="Models.zip") | .id')
          
          if [ -z "$ASSET_ID" ] || [ "$ASSET_ID" == "null" ]; then
            echo "Could not find Models.zip in release assets"
            exit 1
          fi
          
          echo "Downloading asset ID: $ASSET_ID"
          curl -LJ \
            -H "Accept: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/davidcamick/camstem/releases/assets/$ASSET_ID" \
            -o Models.zip

          if [ ! -f Models.zip ]; then
            echo "Failed to download Models.zip"
            exit 1
          fi

          rm -rf Models
          unzip -q Models.zip -d .
          rm Models.zip

      # 7) Install dependencies
      - name: Install dependencies
        run: npm install

      # 8) Build & publish
      - name: Build Mac (publish to GitHub)
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # Apple Developer email
          APPLE_ID: ${{ secrets.APPLE_ID }}

          # Electron-builder 25+ expects these EXACT variable names
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
