name: Build & Publish CamStem

on:
  push:
    tags:
      - "v*"  # e.g. v0.9.8, v1.0.0, etc.

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Configure GH_TOKEN
        # Pass the GH_TOKEN secret to electron-builder so it can publish
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Build for current OS
        run: |
          # On macOS, run the "build:mac" script and force publish
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run build:mac -- --publish=always
          else
            # On Windows, your "build:win" script already has --publish=always
            npm run build:win
          fi
